---
- name: "copy artifact into the server"
  become: true
  copy:
    src: artifact.tar.gz
    dest: ~/

- name: extract zipped artifact and install dependancies
  become: true
  shell: |
    tar -xvzf artifact.tar.gz
    npm install


- name: start app
  become: true
  shell: |
    pm2 stop default
    pm2 start npm -- start