---
- name: create ~/backend directiory
  become: true
  shell:  mkdir ~/backend

- name: "copy artifact into the server"
  become: true
  copy:
    src: artifact.tar.gz
    dest: ~/backend
    backup: yes

- name: extract zipped artifact and install dependancies
  become: true
  shell: |
    cd backend
    tar -xvzf artifact.tar.gz
    ls artifact
    npm install


- name: start app
  become: true
  shell: |
    pm2 stop default
    pm2 start npm -- start