---
- name: "copy artifact into the server"
  become: true
  copy:
    src: files/artifact.tar.gz
    dest: ~/

- name: extract zipped artifact and install dependancies
  become: true
  shell: |
    tar -xvzf ~/artifact.tar.gz

- name: start app
  become: true
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start