---
- name: "copy artifact into the server"
  become: true
  copy:
    src: artifact.tar.gz
    dest: /artifact.tar.gz
    backup: yes

- name: extract zipped artifact
  become: true
  shell: |
    tar -xvzf artifact.tar.gz .

- name: install dependancies
  become: true
  shell: |
    npm install

- name: start app
  become: true
  shell: |
    pm2 stop default
    pm2 start
    npm start
